### ISSUE TITLE
Execute doesn't use the return value

### ISSUE THREAD

**Issue by deanebarker** [statiqdev/Statiq#198] opened 2016-01-29 17:56 UTC
Consider this pipeline:

```
Pipelines.Add("Source",
    Documents(1),
    Trace("This displayed, so there's something in the pipeline..."),
    Execute((d,c) => { return d; } ),
    Trace("There is now nothing in the pipeline, so this won't display...")
);
```

I have confirmed in the code above -- and in another project -- that `Execute` with a `DocumentConfig` delegate doesn't actually use the return value.  Calls to `Execute` seem to empty the pipeline.

I looked through the `Execute` module, and everything looks fine.  The operative line is here:

```
return inputs.SelectMany(x => _executeDocuments.Invoke<IEnumerable<IDocument>>(x, context) ?? Array.Empty<IDocument>());
```

What am I missing?

**Comment by deanebarker** [comment] 2016-01-29 18:44
I debugged and confirmed that `inputs` has 1 item, but the lambda is returning 0.  So it's taking in 1 and returning nothing, which is weird because all the `DocumentConfig` does is return what it's given in this case.

**Comment by deanebarker** [comment] 2016-01-29 18:54
I see the problem.  I should be returning an `IEnumerable<IDocument>`, not just an `IDocument`.  I'm confused, then, how the config got through compilation.

**Comment by daveaglick** [comment] 2016-01-29 19:00
Just looking at this. Your fix will get past the problem and get you working, but there's still a bug here.

The `Invoke<T>()` extension method for invoking the config delegates uses a call to `IExecutionContext.TryConvert()` to try and get the value. This in turn calls the super-neat convert-anything-to-anything-else library which, among other conversions, should be turning a single document into the requested type of `IEnumerable<IDocument>` for us. It's the last section of `Wyam.Core.TypeHelper.TryConvert<T>()` that's failing.

**Comment by deanebarker** [comment] 2016-01-29 19:02
Call this "debugging hindrance." When it executed, I assume I had the syntax right....

**Comment by daveaglick** [comment] 2016-01-29 19:05
> I'm confused, then, how the config got through compilation.

The Execute module (like many of them) actually takes a `DocumentConfig` delegate which is defined as:

```
public delegate object DocumentConfig(IDocument doc, IExecutionContext ctx);
```

Notice that it just returns an `object`. The conversion to the desired type is actually performed on the fly during execution by the `Invoke<T>()` extension for `DocumentConfig` and it's up to each module to decide what to do if that fails.

> Call this "debugging hindrance." When it executed, I assume I had the syntax right....

Yeah, there's ups and downs to the current approach. On the plus side, we can currently allow the delegates to be very flexible. I.e., you could return the string `"2"` when the module actually needs an `int`. On the other hand, you get failures like this when you think you're returning the right thing but it can't be converted to what the module is expecting.

**Comment by daveaglick** [comment] 2016-01-29 23:00
For future reference in case I need it - repro (LINQPad):

```
public void Main()
{
    Engine engine = new Engine();
    engine.RootFolder = "C:\\Temp";
    engine.Trace.AddListener(new ConsoleTraceListener());
    engine.Pipelines.Add("Source",
        new Documents(1),
        new Wyam.Core.Modules.Extensibility.Trace("This displayed, so there's something in the pipeline..."),
        new Execute((d, c) => { return d; }),
        new Wyam.Core.Modules.Extensibility.Trace("There is now nothing in the pipeline, so this won't display...")
    );
    engine.Execute();
}
```

**Comment by daveaglick** [comment] 2016-01-30 21:20
Found the underlying bug. The problem is that in addition to attempting to convert a single atomic type into an enumerable if that's what's requested, the sometimes-too-clever universal type conversion logic will also attempt to convert an enumerable of one type into an enumerable of a different type. In this case, the single `IDocument` that's being returned by the delegate is _itself_ an enumerable of metadata. The type converter is attempting to convert the document _as an enumerable of metadata_ into an enumerable of `IDocument`. The converter returns an enumerable of all the items which could be successfully converted, and in this case since none of the metadata in the document are themselves `IDocument` instances, the converter returns an empty enumerable.

The fix is going to be to add an extra check so the conversion process first checks if the instance being converted to an enumerable is of the type of the requested enumerable _before_ treating it as an enumerable itself and attempting to convert it's items.

Should have the fix committed soon.

**Closed as completed** 2016-01-30 22:25 UTC
Labels: ⚠️ Bug
