### ISSUE TITLE
Problem with nightly builds Cake.Common not found

### ISSUE THREAD

**Issue by LokiMidgard** [statiqdev/Statiq#291] opened 2016-05-18 13:59 UTC
Hi,

I tried to use the nightly Builds, but getting an error I'm not sure about where it came from.
Cake don't find dependency Cake.Common when tried to install Cake.Wyame:

```
Installing 'Cake 0.11.0'.
Successfully installed 'Cake 0.11.0'.
Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
Unable to resolve dependency 'Cake.Common (= 0.10.1)'.
Error: Failed to install addin 'Cake.Wyam'.
```

Not sure what I'm missing. I used the feeds that where posted in #134

**Comment by daveaglick** [comment] 2016-05-18 14:28
Pretty sure I know what the problem is. When I tested using the development feed yesterday, I had already run Cake previously so it had already downloaded `Cake.Common` before I changed the feed endpoint. I suspect that without `Cake.Common` already being on disk, Cake is attempting to resolve the dependency using the same endpoint as the addin, which obviously doesn't contain the actual Cake libraries since it's a Wyam-only feed. I was able to replicate by changing to the Wyam dev feed for the addin and totally deleting the existing Cake libraries from the tools folder.

To resolve, add the `Cake.Common` library using the `#addin` directive before the directive for `Cake.Wyam`. That will make sure the Cake library is downloaded from the normal NuGet gallery feed before downloading `Cake.Wyam` from the Wyam dev feed.

The top of your Cake build script should look like this:

```
#tool nuget:https://www.myget.org/F/wyam/api/v2?package=Wyam&prerelease
#addin nuget:?package=Cake.Common
#addin nuget:https://www.myget.org/F/wyam/api/v2?package=Cake.Wyam&prerelease
```

cc @patriksvensson - I know you're working on some of the NuGet stuff and thought this edge case might interest you. If you've specified an addin from an alternate source, should the primary source(s) still be checked for dependency resolution?

**Comment by LokiMidgard** [comment] 2016-05-18 14:41
Thanks for the fast response, I tried your approche. But it resulted in following error:

```
Error: error CS1704: An assembly with the same simple name 'Cake.Common' has already been imported. Try removing one of the references (e.g. 'c:\Users\Patrick\Source\Repos\nota\Tools\Cake\Cake.Common.dll') or sign them to enable side-by-side.
```

**EDIT**
However it worked when I used the normal nugget fed and then only deleted the Wyam tools.

**Comment by daveaglick** [comment] 2016-05-18 14:45
Maybe there's still some stale packages from the previous try. Can you try running one more time after deleting everything under the `tools` folder (except for `packages.config`)? Let me know if that does the trick - if not I'll start digging deeper...

I'm a big fan of the Cake build setup, so while there's some initial kinks to work out with this first version of the integration, I think it'll really help in the long run to enable deployment scenarios that Wyam doesn't handle directly.

**Comment by daveaglick** [comment] 2016-05-18 14:48
Nevermind - I was able to replicate your second problem... Let me keep digging...

**Comment by daveaglick** [comment] 2016-05-18 15:34
@LokiMidgard Okay, you should be good to go now. Might need to delete that `tools` folder one more time (except for `packages.config`). It turns out you don't need to add the extra directive after all, just put this at the top of your build script:

```
#tool nuget:https://www.myget.org/F/wyam/api/v2?package=Wyam&prerelease
#addin nuget:https://www.myget.org/F/wyam/api/v2?package=Cake.Wyam&prerelease
```

I was able to resolve the problem by just totally removing the dependency on `Cake.Common` from `Cake.Wyam` since it stands to reason that `Cake.Wyam` will always be used with the Cake engine, which will have already referenced `Cake.Wyam`. There's a new build on the Wyam dev feed that reflects this.

**Comment by daveaglick** [comment] 2016-05-18 15:38
@patriksvensson Even though this particular issue was easily resolved by removing the dependency on `Cake.Common` from the addin (also see cake-build/cake#895 to make this explicit for other addin developers), I think the original question about which feeds addins loaded from alternate package sources should use for restoring dependencies is still a valid one. The original issue could have happened just as easily if the addin referenced some other package from the public NuGet gallery but was installed from a development/alternative package source.

**Closed as completed by daveaglick** 2016-05-18 15:38 UTC
Labels: Discussion/Question

**Comment by LokiMidgard** [comment] 2016-05-18 16:59
Thanks.

Works perfectly. But  I don't have a `packages.config` anywhere in my folders. For what should there be one. All references are added in the cake file, or the wyam config. Maybe I'm missing something important.

**Comment by daveaglick** [comment] 2016-05-18 17:10
My `tools\packages.config` just has a reference to Cake, but the bootstrapper pulls that down anyway so to be honest, I'm not even sure why it's there...If it works, it works :)
