### ISSUE TITLE
Any way to disable "Installing NuGet packages" and use the cached files

### ISSUE THREAD

**Issue by AllanXu49** [statiqdev/Statiq#434] opened 2017-02-06 02:43 UTC
Is there any way have Wyam not install Nuget pages on every run? 
At this point I have to wait ~15 seconds for packages to run:

```
Installing NuGet packages
    Installing packages to C:/Users/userABC/.nuget/packages (using global packages folder)
    NuGet packages installed in 14884 ms
```

**Comment by daveaglick** [comment] 2017-02-07 14:43
There's not really a way to turn it off. The issue is being worked on in #317 and I'm hoping to have some relief for this soon.

There is a hacky way to reduce the time it takes. If you install all the NuGet packages you need and then manually extract the assemblies they contain you can remove `--nuget` (on the CLI) or `#n` (in the config file) and use `--assembly` (on the CLI) or `#a` (in the config file) to reference the assemblies directly. This only works for custom configs though - the NuGet references are baked into the recipes.

**Comment by AllanXu49** [comment] 2017-02-07 15:28
Hi David,

Thank you for the update. It might help if Wyam follows the similar pattern that Hexo implements when it works with npm. 

I think Hexo is the fastest static site generator available. It produces the large site in subsecond where other site generators do the same work in 10~15 seconds. Hero checks npm only at he 1st run.

**Comment by daveaglick** [comment] 2017-02-24 18:46
This is now resolved in the develop branch - after the first run, the NuGet dependency tree is cached and won't be reconstructed.

**Closed as completed by daveaglick** 2017-02-24 18:46 UTC
Labels: Discussion/Question
