### ISSUE TITLE
Summary not shown

### ISSUE THREAD

**Issue by pascalberger** [statiqdev/Statiq#483] opened 2017-03-21 22:12 UTC
In certain cases the summary doesn's show up in the documentation. See https://cake-contrib.github.io/Cake.Prca.Website/api/Cake.Prca.Issues.MsBuild/LogFileFormat/. 

Source code is here: https://github.com/cake-contrib/Cake.Prca.Issues.MsBuild/blob/develop/src/Cake.Prca.Issues.MsBuild/LogFileFormat.cs.

Site is generated by using assemblies from downloaded NuGet packages, which contains the documentation: https://www.nuget.org/packages/Cake.Prca.Issues.MsBuild/

**Comment by daveaglick** [comment] 2017-03-27 17:53
I can't reproduce at this point, and I see that the linked page does include summary information now. Has anything changed with this issue?

**Comment by pascalberger** [comment] 2017-03-27 19:08
The issue seems to be flaky, and the site was rebuild a few times since I created the issue. It seems to appear quite often though if I run the preview server (calling `.\build.ps1 -target preview`) after some changes are made and the site is recompiled. After cancelling the Cake script and restarting it, all issues are back in this case.

Not sure if it is the same issue though, since in the original issue it happened without the preview server.

**Comment by pascalberger** [comment] 2017-03-27 21:18
@daveaglick It just happened again. This time documentation for `PrcaAliases`: https://cake-contrib.github.io/Cake.Prca.Website/api/Cake.Prca/PrcaAliases/

**Comment by daveaglick** [comment] 2017-03-27 21:37
It's strange - I've also been able to get it to happen, but not consistently. That suggests something with concurrency. I've also tracked it down to the bit that associates the content of the XML documentation file with a symbol - it finds and reads the file just fine, and the correct content is in it.

**Comment by daveaglick** [comment] 2017-03-27 21:44
Pretty sure I've got this pinned done, at least enough that I'm comfortable closing the issue. I've tracked it back to the fact that we've got multiple XML documentation files and they're tightly interrelated so the XML documentation provider gets confused with concurrent doc fetching across files.

If you continue to see missing documentation after the next release, please reopen or open a new issue so we can continue working the problem.

**Closed as completed** 2017-03-27 21:47 UTC
Labels: ⚠️ Bug

**Comment by daveaglick** [comment] 2017-03-28 15:47
Fixed with a lock around the call to get XML comments for a symbol, but tracking in Roslyn at https://github.com/dotnet/roslyn/issues/18244
