### ISSUE TITLE
Cannot build Wyam from source on OSX under Mono

### ISSUE THREAD

**Issue by positivejam** [statiqdev/Statiq#278] opened 2016-04-22 16:31 UTC
I could use some help getting Wyam working on OS X. To do this I'm assuming I'll need to build from source, but have had some trouble with that.

I wrote up a detailed question already, but before submitting, wanted to ask if this is the preferred channel through which to ask questions like this? Would StackOverflow be better? Some place else?

Very interested in Wyam but have not as yet been able to get it running on OS X. Thanks!

**Comment by daveaglick** [comment] 2016-04-22 16:36
GitHub Issues are fine for general questions (I even have a label for them). The Gitter room is also another good place for quick questions too: https://gitter.im/Wyamio/Wyam.

Unfortunately we're not ready for cross-platform use quite yet. It _may_ work on a Mono stack, but I've never tested it or even tried to build. The plan right now is to support .NET Core relatively soon after release, at least for the core parts of Wyam. The issue is complicated because Wyam makes use of so many third-party libraries for doing things like parsing Markup and processing YAML. The transition to full cross-platform .NET Core will happen bit by bit as those third-party libraries start to support it.

Curious what specific compilation error you encountered? Were you attempting to build with Mono?

**Comment by positivejam** [comment] 2016-04-22 16:51
I was pretty sure that the project didn't have cross-platform support yet, but [this post](https://github.com/Wyamio/Wyam/issues/246) gave me reason to think that some folks have been messing around with it, so I thought I'd ask.

Also, yes, I was attempting to build with Mono. Here's a sample of the output at the point at which the build stalled out:

```
Executing task: Restore-NuGet-Packages
Executing: /Users/j7kohl/Desktop/Wyam-0.12.0-beta-source/tools/NuGet.exe restore "/Users/j7kohl/Desktop/Wyam-0.12.0-beta-source/src/Wyam.sln" -NonInteractive
MSBuild auto-detection: using msbuild version '4.0' from '/usr/local/Cellar/mono/4.2.3.4/lib/mono/4.5'.
Feeds used:
  /Users/j7kohl/.local/share/NuGet/Cache
  /Users/j7kohl/.nuget/packages/
  https://api.nuget.org/v3/index.json

Restoring NuGet package Microsoft.CodeAnalysis.Analyzers.1.0.0.
Restoring NuGet package Microsoft.CodeAnalysis.1.0.0.
Restoring NuGet package Microsoft.CodeAnalysis.Common.1.0.0.
Restoring NuGet package Microsoft.CodeAnalysis.CSharp.1.0.0.
Restoring NuGet package Microsoft.CodeAnalysis.CSharp.Workspaces.1.0.0.
Restoring NuGet package Microsoft.CodeAnalysis.VisualBasic.1.0.0.
Restoring NuGet package Microsoft.CodeAnalysis.VisualBasic.Workspaces.1.0.0.
Restoring NuGet package Microsoft.CodeAnalysis.Workspaces.Common.1.0.0.
Restoring NuGet package Microsoft.Composition.1.0.27.
Restoring NuGet package Microsoft.Owin.3.0.1.
Restoring NuGet package Microsoft.Owin.FileSystems.3.0.1.
Restoring NuGet package Microsoft.Owin.Host.HttpListener.3.0.1.
Restoring NuGet package Microsoft.Owin.Hosting.3.0.1.
Restoring NuGet package Microsoft.Owin.StaticFiles.3.0.1.
Restoring NuGet package Owin.1.0.0.
Restoring NuGet package System.Collections.Immutable.1.1.36.
```

After that it just hung there. I should probably note that this is the first time I've attempted to build a Mono project at all, so I'm not exactly in my wheelhouse.

**Comment by daveaglick** [comment] 2016-04-22 17:05
Interesting - that almost sounds like it's NuGet or [Cake](http://cakebuild.net) (the build engine we're using) that got hung. I would have expected to see an exception if the actual build failed. Though maybe there's something that has to be done to rig Cake up to build with the Mono compiler.

@eatdrinksleepcode - do you recall how far you made it building Wyam on OSX?

**Comment by positivejam** [comment] 2016-04-22 17:12
Whoa, just tried it again, very different results. The build script made it a lot further, eventually to this:

```
Executing task: Build
Executing: /usr/local/bin/xbuild /v:minimal /p:"Configuration"="Release" /t:Build "/Users/j7kohl/Desktop/Wyam-0.12.0-beta-source/src/Wyam.sln"
XBuild Engine Version 12.0
Mono, Version 4.2.3.0
Copyright (C) 2005-2013 Various Mono authors
        Configuration: Release Platform: AnyCPU
/usr/local/Cellar/mono/4.2.3.4/lib/mono/xbuild/12.0/bin/Microsoft.Common.targets:  warning : TargetFrameworkVersion 'v4.6' not supported by this toolset (ToolsVersion: 12.0).
/usr/local/Cellar/mono/4.2.3.4/lib/mono/xbuild/12.0/bin/Microsoft.Common.targets:  warning : Unable to find framework corresponding to the target framework moniker '.NETFramework,Version=v4.6'. Framework assembly references will be resolved from the GAC, which might not be the intended behavior.
CSC: error CS0518: The predefined type `System.Object' is not defined or imported
CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
CSC: error CS0518: The predefined type `System.Single' is not defined or imported
CSC: error CS0518: The predefined type `System.Double' is not defined or imported
CSC: error CS0518: The predefined type `System.Char' is not defined or imported
CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
CSC: error CS0518: The predefined type `System.String' is not defined or imported
CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
CSC: error CS0518: The predefined type `System.Void' is not defined or imported
CSC: error CS0518: The predefined type `System.Array' is not defined or imported
CSC: error CS0518: The predefined type `System.Type' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.Exception' is not defined or imported
An error occured when executing task 'Build'.
Error: Cake.Core.CakeException: XBuild: Process returned an error.
  at Cake.Core.Tooling.Tool`1[TSettings].Run (Cake.Core.Tooling.TSettings settings, Cake.Core.IO.ProcessArgumentBuilder arguments, Cake.Core.IO.ProcessSettings processSettings, System.Action`1 postAction) <0x110df1990 + 0x00186> in <filename unknown>:0 
  at Cake.Core.Tooling.Tool`1[TSettings].Run (Cake.Core.Tooling.TSettings settings, Cake.Core.IO.ProcessArgumentBuilder arguments) <0x110df1950 + 0x00023> in <filename unknown>:0 
  at Cake.Common.Tools.XBuild.XBuildRunner.Run (Cake.Core.IO.FilePath solution, Cake.Common.Tools.XBuild.XBuildSettings settings) <0x111081950 + 0x0003a> in <filename unknown>:0 
  at Cake.Common.Tools.XBuild.XBuildAliases.XBuild (ICakeContext context, Cake.Core.IO.FilePath solution, Cake.Common.Tools.XBuild.XBuildSettings settings) <0x1110816d0 + 0x000fa> in <filename unknown>:0 
  at CakeBuildScriptImpl.XBuild (Cake.Core.IO.FilePath solution, Cake.Common.Tools.XBuild.XBuildSettings settings) <0x111081680 + 0x00038> in <filename unknown>:0 
  at CakeBuildScriptImpl+<Execute>c__AnonStorey0.<>m__4 () <0x1110811e0 + 0x00152> in <filename unknown>:0 
  at Cake.Core.CakeTaskBuilderExtensions+<>c__DisplayClass4.<Does>b__3 (ICakeContext context) <0x110dee750 + 0x00019> in <filename unknown>:0 
  at Cake.Core.ActionTask.Execute (ICakeContext context) <0x110dee670 + 0x00063> in <filename unknown>:0 
  at Cake.Core.DefaultExecutionStrategy.Execute (Cake.Core.CakeTask task, ICakeContext context) <0x110dee440 + 0x001ae> in <filename unknown>:0 
  at Cake.Core.CakeEngine.ExecuteTask (ICakeContext context, IExecutionStrategy strategy, System.Diagnostics.Stopwatch stopWatch, Cake.Core.CakeTask task, Cake.Core.CakeReport report) <0x110deddb0 + 0x000dd> in <filename unknown>:0 
```

Not sure why it would have needed a couple tries to get far enough to output an exception.

**Comment by positivejam** [comment] 2016-04-22 17:14
But I guess I can't pull down `System` namespaces.

**Comment by daveaglick** [comment] 2016-04-22 17:21
I'll take a wild guess that it's failing because of this: `TargetFrameworkVersion 'v4.6' not supported by this toolset`. I thought Mono did have support for 4.6, but perhaps there's some mismatch between the project file and what Mono expects to see. That would also help explain the failure to import core types - if the frameworks are mismatched then the compiler might be looking for the wrong BCL.

My experience starts to fall off dramatically at this point. I did a lot of work with Mono on Linux four or five years ago, but I've lost most that by now :). I'll take a look if I get a free moment, but it might be a little while. In the meantime, I'll keep this issue open in case someone else has already gone down this path. It's probably not a bad idea to investigate anyway - it would be cool to get Mac/Linux support up and running if everything does work under Mono with limited changes.

**Comment by positivejam** [comment] 2016-04-22 17:24
Thanks for your help, Dave. If I figure anything out, I'll post it here.

**Comment by daveaglick** [comment] 2016-04-22 17:29
:thumbsup:

**Comment by eatdrinksleepcode** [comment] 2016-04-27 07:40
Mono _does_ support 4.6, but not _as_ 4.6. It's weird, but Mono supports .NET Framework 4.6 (and 4.5.1 and 4.5.2) all under the TargetFrameworkVersion "v4.5". This makes supporting both .NET and Mono builds in the same code base difficult. I have done it by making the TargetFrameworkVersion conditional and setting it via build script (you can see an example [here](https://github.com/eatdrinksleepcode/casper/blob/master/Console/Console.csproj) and [here](https://github.com/eatdrinksleepcode/casper/blob/master/build.cmd)); but that doesn't play very well with IDEs on whichever platform you don't default to. It might work to default TargetFrameworkVersion based on OS or directly on the presence of Mono instead, but I haven't tried that yet. I do know that some other projects handle this by maintaining two different sets of projects.

I have been meaning to submit a PR to Wyam to at least allow command line build on Mono even if it doesn't play that well with Mono IDEs; but a new work project has been taking up my time. I might try to get to it in a week or two.

**Comment by daveaglick** [comment] 2016-05-23 01:17
I'm going to close this particular issue - I've opened #300 to consolidate tracking work regarding .NET Core support. I suspect that this will be the officially supported approach to cross platform support. I'm just not sure there's much value in focusing on Mono with Core around the corner.

**Closed as completed by daveaglick** 2016-05-23 01:17 UTC
Labels: Discussion/Question
