### ISSUE TITLE
.NET 6 support

### ISSUE THREAD

**Issue by petrsvihlik** [statiqdev/Statiq#964] opened 2021-10-01 20:26 UTC
Hey @daveaglick!
Have you tried Statiq with .NET 6 already?

When I switch the target framework of my [project](https://github.com/petrsvihlik/petrsvihlik.com) to .NET 6, the generation starts failing with:

>[CRIT] Object does not match target type.

> [ERRO] XYZPipeline/Process » RenderRazor » [=> posts/mypost.html] Object does not match target type.

Is there anything I can do about it atm?

**Comment by daveaglick** [comment] 2021-10-01 20:34
I love being able to say a problem is fixed as soon as it's reported! :)

We tracked a root cause for this in https://github.com/statiqdev/Statiq.Framework/issues/204 - it was a pretty interesting one due (partly) to an upstream bug in the .NET Razor engine itself. In any case, a fix is in main and has been confirmed, I just need to get the code to a releasable state due to some other concurrent work I'm doing. I'll likely have a release out this weekend or early next week at the latest.

**Closed as completed by daveaglick** 2021-10-01 20:34 UTC

**Comment by petrsvihlik** [comment] 2021-10-02 06:51
Oh, that's perfect! Reading the discussion, it's an interesting problem
indeed.
