### ISSUE TITLE
Formatting issues with code samples on reactiveui.net

### ISSUE THREAD

**Issue by ghuntley** [statiqdev/Statiq#550] opened 2017-08-13 03:02 UTC
Might have found a problem in the markdown renderer:

See https://github.com/reactiveui/website/issues/20#issuecomment-322017389

GitHub Markdown:
```
ObservableAsPropertyHelper<List<FlickrPhoto>> _SearchResults; 
```
Outputs HTML as:
```
ObservableAsPropertyHelper> _SearchResults;
```

**Comment by daveaglick** [comment] 2017-08-13 03:17
Yuck, that's not good at all. I'll take a look as soon as I can (probably Monday) and get a patch release out.

**Comment by daveaglick** [comment] 2017-08-14 13:44
Here's what I'm seeing in the HTML:

```
    public ReactiveCommand<string, list<flickrphoto="">&gt; ExecuteSearch { get; protected set; }
```

That's obviously not right, the angle brackets should be escaped. What's interesting is that `List<FlickrPhoto>>` has been lowercased and changed with an extra `=""`. That's not just lack of proper escaping, that's something actively changing content. Working theory right now is that the code here has somehow triggered one of the  MarkDig extensions and it's interpreting the Markdown differently.

BTW, off topic but did you notice classes from the API are linked? It's easy to miss in code blocks since there's no special styles applied but you can click on `ReactiveObject` and it'll take you to the API page.

**Comment by daveaglick** [comment] 2017-08-14 15:16
So, about that nice `ReactiveObject` link...turns out that's actually the problem. To find and replace API class names we load the entire page into AngleSharp and then use DOM queries to manipulate it. Even though everything that isn't an API class name is left alone it looks like AngleSharp is manipulating the page in other places during the round trip.

A temporary workaround is to disable API class name linking using:
```
Settings[DocsKeys.AutoLinkTypes] = false;
```

That said, now that I know where the problem is, I hope to have a new release out later today or tomorrow with a permanent fix.

**Comment by daveaglick** [comment] 2017-08-14 16:13
Fix is in, will go out with next release soon.

**Closed as completed** 2017-08-14 16:12 UTC
Labels: ⚠️ Bug
