### ISSUE TITLE
Upgrading to 2.0 using choco - Issue and solution

### ISSUE THREAD

**Issue by tesar-tech** [statiqdev/Statiq#753] opened 2018-11-26 16:50 UTC
(Maybe useful for someone)

After upgrading using `choco upgrade wyam` command and running wyam with `wyam -p -w` I got error:
```
Cannot find file at '..\\lib\wyam\Wyam.exe' (C:\ProgramData\chocolatey\lib\wyam\Wyam.exe). This usually indicates a missing or moved file.
```
So I uninstalled wyam with `choco uninstall wyam` and installed it with `dotnet tool install -g Wyam.Tool`.
But error about missing wyam.exe file was still present.

Solution is to **manually delete wyam.exe** from `C:\ProgramData\chocolatey\bin` (I think uninstaller should do this but obviously it did not). After that wyam should run without issue.

**Comment by gep13** [comment] 2018-11-27 08:54
@tesar-tech yes, the Chocolatey uninstallation should have removed that shim exe, so not sure why it didn't

**Comment by daveaglick** [comment] 2018-11-29 19:50
Thanks for the report - hopefully others will find it useful if needed. I'll label this as a bug, but I'm going to close it since I don't really know the first thing about Chocolatey and @gep13 (who is on the Chocolatey team) indicates this was unexpected behavior. I'll revisit if I get more reports of this problem, but for now hopefully this issue is sufficient if anyone else runs across it.

**Closed as completed by daveaglick** 2018-11-29 19:50 UTC
Labels: ⚠️ Bug
