### ISSUE TITLE
Wyam build/re-build callbacks

### ISSUE THREAD

**Issue by avishnyakov** [statiqdev/Statiq#264] opened 2016-03-28 04:04 UTC
Is it possible to handle Wyam build/re-build events in PowerShell? Here is why it might be a good idea at least for our editing workflow:

We have the following PS script to start up the Wyam site:

``` ps
Start-Process "chrome.exe" http://localhost:5080
. "$PSScriptRoot\$wyam\Wyam.exe"  --input "$PSScriptRoot\Views" --output "$PSScriptRoot\Views-Output" --preview --watch --config "_site.wyam" 
```

Next, we edit MD/Razor files and Wyam picks it up, automatically. The only thing is that we need to switch the windows to get back to PowerShell and check is it has already finished, or there were some errors. 

That could be much more efficient it Wyam had some callback, so that we would be able to handle them in the PS script and then notify (say, via pops up message API in windows) that site is rebuilding or has been built.

Understand that could be something weird we wish. Putting it here to discuss and learn how other folks handle editing workflow :)

**Comment by daveaglick** [comment] 2016-04-18 16:54
Not sure what this would look like under the hood. We have an open issue for events in the engine (#192), but I've never seen any sort of PowerShell-enabled callback or event mechanism. Do you know of another PowerShell tool that provides "callbacks"? How does it work? How do you handle the callbacks in PowerShell?

**Comment by daveaglick** [comment] 2016-05-07 01:02
Considering this a duplicate of #192 - I'll make a comment over there about looking at surfacing events to PowerShell callers.

**Closed as completed** 2016-05-07 01:02 UTC
Labels: Discussion/Question
