### ISSUE TITLE
IO exceptions when theme folder is under root folder

### ISSUE THREAD

**Issue by AllanXu49** [statiqdev/Statiq#414] opened 2017-01-25 00:28 UTC
I am preparing a theme for Wyam. It is looking nice and going great so far since I already know Razor well. That is the advantage I did not have with Hexo or Jekyll.

One outstanding question is that how designers can pack and share their Wyam themes?

My theme includes the following files and I have to xcopy (with overwrite) the files to the input folder.

```
\input\_Footer.cshtml
\input\_Head.cshtml
\input\_Header.cshtml
\input\_IndexHeader.cshtml
\input\_Layout.cshtml
\input\_Navbar.cshtml
\input\_PostFooter.cshtml
\input\_PostHeader.cshtml
\input\_PostLayout.cshtml
\input\_PostList.cshtml
\input\_Scripts.cshtml
\input\_Sidebar.cshtml
\input\assets\css\bootstrap.min.css
\input\assets\css\modern-business.css
\input\assets\js\bootstrap.min.js
\input\assets\js\jquery.min.js

```

Hexo or Jekyll have quite mature way of using an available theme without mixing the theme files with the other site files. Since the theme files are in a separate folder, it is easily possible to have multiple themes available for a site and rapidly switch between them in the config.yml file. 

Does such concept or idea available in Wyam?
Are we going to have something like below for Wyam?
https://hexo.io/themes/

**Comment by daveaglick** [comment] 2017-01-25 23:15
There are some instructions here: https://wyam.io/docs/extensibility/creating-a-theme (third paragraph). In general, if you want to package a theme for other people to use just create a NuGet package with [content files](http://blog.nuget.org/20160126/nuget-contentFiles-demystified.html). Wyam will automatically add the content files to the set of input paths, thus "activating" your theme. All your theme users need to do is add the theme package to their Wyam config file (or command line arguments).

You can also test out how a theme will work and keep it separate from your input folder with the `-t` command line argument. If you give that a folder (something like `-t ../mytheme`) then whatever files are in that folder will be used as the theme for that build.

**Comment by daveaglick** [comment] 2017-01-25 23:17
With regard to a themes directory, I'd love to have something like that. At the moment there just aren't enough themes to make a large directory worth it. Once we get a couple more I'll rethink how they're presented on the site.

**Comment by AllanXu49** [comment] 2017-01-26 02:57
Hi David,

Thank you for help.

When I have the Themes folder beside The input folder like below:

```
.\input\
.\output\
.\themes\
.\themes\MyNewTheme
.\config.wyam

```

Then run Wyam:
`wyam --preview --watch  --recipe Blog --theme themes\MyNewTheme
`

I get a series of System.IO.IOException like below

`Exception during execution: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:/_W/XYZBlogT/themes/MyNewTheme/assets/css/MyNewTheme.css' because it is being used by another process.
`
I get above exception for almost every file in my theme folder.

However, if I have the theme folder somewhere outside the the root (where config file resides) i can render the site with no problem

I prefer to have all files related to my site in a single folder as opposed to having the theme folder somewhere else. Is there any way to do that?

Thank you,

**Comment by daveaglick** [comment] 2017-01-26 03:12
Yikes. That's not good. This scenario should be supported, so this is definitely a bug.

When you start Wyam it prints out some stuff under the logo like root path, input paths, etc. Can you please paste that information into this issue? Meanwhile I'll try to reproduce the problem locally.

**Comment by AllanXu49** [comment] 2017-01-26 03:31
Here:

```

$ ..\wyam\wyam --preview --watch  --recipe Blog --theme .\themes\MyTheme1
Wyam version 0.15.8-beta

   ,@@@@@       /@\        @@@@@
   @@@@@@      @@@@@|     $@@@@@h
  $@@@@@     ,@@@@@@@    g@@@@@P
 ]@@@@@M    g@@@@@@@    g@@@@@P
 $@@@@@    @@@@@@@@@   g@@@@@P
j@@@@@   g@@@@@@@@@p ,@@@@@@@
$@@@@@g@@@@@@@@B@@@@@@@@@@@P
`$@@@@@@@@@@@`  ]@@@@@@@@@`
  $@@@@@@@P`     ?$@@@@@P
    `^``           *P*`
**BUILD**
Loading configuration from file:///C:/_W/XyzBlogT/config.wyam
Installing NuGet packages
    Installing packages to C:/Users/XYZUser/.nuget/packages (using global packages folder)
    NuGet packages installed in 15108 ms
Recursively loading assemblies
    Assemblies loaded in 382 ms
Cataloging classes
    Classes cataloged in 261 ms
Evaluating configuration script
    Evaluated configuration script in 2408 ms
Root path:
  file:///C:/_W/XyzBlogT
Input path(s):
  themes/MyTheme1
  theme
  input
Output path:
  output
Cleaning output path output
Cleaned output directory
Executing 9 pipelines
    Executing pipeline "Pages" (1/9) with 9 child module(s)
        Executed pipeline "Pages" (1/9) in 183 ms resulting in 16 output document(s)
    Executing pipeline "RawPosts" (2/9) with 9 child module(s)
        Executed pipeline "RawPosts" (2/9) in 235 ms resulting in 64 output document(s)
    Executing pipeline "Tags" (3/9) with 10 child module(s)
        Executed pipeline "Tags" (3/9) in 2729 ms resulting in 106 output document(s)
    Executing pipeline "Posts" (4/9) with 6 child module(s)
        Executed pipeline "Posts" (4/9) in 1410 ms resulting in 64 output document(s)
    Executing pipeline "Feed" (5/9) with 3 child module(s)
        Executed pipeline "Feed" (5/9) in 126 ms resulting in 2 output document(s)
    Executing pipeline "RenderPages" (6/9) with 3 child module(s)
            Ignoring 12 inputs due to source file name prefix
        Executed pipeline "RenderPages" (6/9) in 308 ms resulting in 4 output document(s)
    Executing pipeline "Redirects" (7/9) with 4 child module(s)
        Executed pipeline "Redirects" (7/9) in 13 ms resulting in 0 output document(s)
    Executing pipeline "Resources" (8/9) with 1 child module(s)
            Error while executing module CopyFiles
        Error while executing pipeline Resources
Exception during execution: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:/_W/XyzBlogT/themes/MyTheme1/assets/css/modern-business.css' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Wyam.Core.IO.FileProviders.Local.LocalFile.<>c__DisplayClass13_0.<CopyTo>b__0() in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.IO.FileProviders.Local.LocalFileProvider.Retry[T](Func`1 func) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFileProvider.cs:line 41
   at Wyam.Core.IO.FileProviders.Local.LocalFile.CopyTo(IFile destination, Boolean overwrite, Boolean createDirectory) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.Modules.IO.CopyFiles.<>c__DisplayClass9_0.<Execute>b__1(IFile file) in E:\Code\Wyam\src\core\Wyam.Core\Modules\IO\CopyFiles.cs:line 133
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNextSlowPath()
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNext()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Wyam.Core.Execution.Pipeline.Execute(ExecutionContext context, IEnumerable`1 modules, ImmutableArray`1 documents) in E:\Code\Wyam\src\core\Wyam.Core\Execution\Pipeline.cs:line 252
   at Wyam.Core.Execution.Pipeline.Execute(Engine engine) in E:\Code\Wyam\src\core\Wyam.Core\Execution\Pipeline.cs:line 146
   at Wyam.Core.Execution.Engine.Execute() in E:\Code\Wyam\src\core\Wyam.Core\Execution\Engine.cs:line 176
---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:/_W/XyzBlogT/themes/MyTheme1/assets/css/modern-business.css' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Wyam.Core.IO.FileProviders.Local.LocalFile.<>c__DisplayClass13_0.<CopyTo>b__0() in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.IO.FileProviders.Local.LocalFileProvider.Retry[T](Func`1 func) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFileProvider.cs:line 41
   at Wyam.Core.IO.FileProviders.Local.LocalFile.CopyTo(IFile destination, Boolean overwrite, Boolean createDirectory) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.Modules.IO.CopyFiles.<>c__DisplayClass9_0.<Execute>b__1(IFile file) in E:\Code\Wyam\src\core\Wyam.Core\Modules\IO\CopyFiles.cs:line 133
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #1) System.IO.IOException: The process cannot access the file 'C:/_W/XyzBlogT/themes/MyTheme1/index.html' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Wyam.Core.IO.FileProviders.Local.LocalFile.<>c__DisplayClass13_0.<CopyTo>b__0() in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.IO.FileProviders.Local.LocalFileProvider.Retry[T](Func`1 func) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFileProvider.cs:line 41
   at Wyam.Core.IO.FileProviders.Local.LocalFile.CopyTo(IFile destination, Boolean overwrite, Boolean createDirectory) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.Modules.IO.CopyFiles.<>c__DisplayClass9_0.<Execute>b__1(IFile file) in E:\Code\Wyam\src\core\Wyam.Core\Modules\IO\CopyFiles.cs:line 133
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #2) System.IO.IOException: The process cannot access the file 'C:/_W/XyzBlogT/themes/MyTheme1/favicon.ico' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Wyam.Core.IO.FileProviders.Local.LocalFile.<>c__DisplayClass13_0.<CopyTo>b__0() in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.IO.FileProviders.Local.LocalFileProvider.Retry[T](Func`1 func) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFileProvider.cs:line 41
   at Wyam.Core.IO.FileProviders.Local.LocalFile.CopyTo(IFile destination, Boolean overwrite, Boolean createDirectory) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.Modules.IO.CopyFiles.<>c__DisplayClass9_0.<Execute>b__1(IFile file) in E:\Code\Wyam\src\core\Wyam.Core\Modules\IO\CopyFiles.cs:line 133
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #3) System.IO.IOException: The process cannot access the file 'C:/_W/XyzBlogT/themes/MyTheme1/assets/css/bootstrap.min.css' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Wyam.Core.IO.FileProviders.Local.LocalFile.<>c__DisplayClass13_0.<CopyTo>b__0() in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.IO.FileProviders.Local.LocalFileProvider.Retry[T](Func`1 func) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFileProvider.cs:line 41
   at Wyam.Core.IO.FileProviders.Local.LocalFile.CopyTo(IFile destination, Boolean overwrite, Boolean createDirectory) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.Modules.IO.CopyFiles.<>c__DisplayClass9_0.<Execute>b__1(IFile file) in E:\Code\Wyam\src\core\Wyam.Core\Modules\IO\CopyFiles.cs:line 133
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #4) System.IO.IOException: The process cannot access the file 'C:/_W/XyzBlogT/themes/MyTheme1/assets/css/clean-blog.css' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Wyam.Core.IO.FileProviders.Local.LocalFile.<>c__DisplayClass13_0.<CopyTo>b__0() in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.IO.FileProviders.Local.LocalFileProvider.Retry[T](Func`1 func) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFileProvider.cs:line 41
   at Wyam.Core.IO.FileProviders.Local.LocalFile.CopyTo(IFile destination, Boolean overwrite, Boolean createDirectory) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.Modules.IO.CopyFiles.<>c__DisplayClass9_0.<Execute>b__1(IFile file) in E:\Code\Wyam\src\core\Wyam.Core\Modules\IO\CopyFiles.cs:line 133
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #5) System.IO.IOException: The process cannot access the file 'C:/_W/XyzBlogT/themes/MyTheme1/assets/css/highlight.css' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Wyam.Core.IO.FileProviders.Local.LocalFile.<>c__DisplayClass13_0.<CopyTo>b__0() in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.IO.FileProviders.Local.LocalFileProvider.Retry[T](Func`1 func) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFileProvider.cs:line 41
   at Wyam.Core.IO.FileProviders.Local.LocalFile.CopyTo(IFile destination, Boolean overwrite, Boolean createDirectory) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.Modules.IO.CopyFiles.<>c__DisplayClass9_0.<Execute>b__1(IFile file) in E:\Code\Wyam\src\core\Wyam.Core\Modules\IO\CopyFiles.cs:line 133
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #6) System.IO.IOException: The process cannot access the file 'C:/_W/XyzBlogT/themes/MyTheme1/assets/css/font-awesome.min.css' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Wyam.Core.IO.FileProviders.Local.LocalFile.<>c__DisplayClass13_0.<CopyTo>b__0() in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.IO.FileProviders.Local.LocalFileProvider.Retry[T](Func`1 func) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFileProvider.cs:line 41
   at Wyam.Core.IO.FileProviders.Local.LocalFile.CopyTo(IFile destination, Boolean overwrite, Boolean createDirectory) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.Modules.IO.CopyFiles.<>c__DisplayClass9_0.<Execute>b__1(IFile file) in E:\Code\Wyam\src\core\Wyam.Core\Modules\IO\CopyFiles.cs:line 133
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

---> (Inner Exception #7) System.IO.IOException: The process cannot access the file 'C:/_W/XyzBlogT/themes/MyTheme1/assets/css/master.css' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Wyam.Core.IO.FileProviders.Local.LocalFile.<>c__DisplayClass13_0.<CopyTo>b__0() in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.IO.FileProviders.Local.LocalFileProvider.Retry[T](Func`1 func) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFileProvider.cs:line 41
   at Wyam.Core.IO.FileProviders.Local.LocalFile.CopyTo(IFile destination, Boolean overwrite, Boolean createDirectory) in E:\Code\Wyam\src\core\Wyam.Core\IO\FileProviders\Local\LocalFile.cs:line 54
   at Wyam.Core.Modules.IO.CopyFiles.<>c__DisplayClass9_0.<Execute>b__1(IFile file) in E:\Code\Wyam\src\core\Wyam.Core\Modules\IO\CopyFiles.cs:line 133
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by daveaglick** [comment] 2017-02-02 21:51
I can replicate this problem and confirm it still exists in 0.16.1. Continuing to research.

**Comment by daveaglick** [comment] 2017-02-02 22:19
Bug is because the default `theme` path has the same starting characters as `themes\MyTheme1` and the logic that figures out which of the many input paths a file is coming from uses a simple `string.StartsWith()`. CopyFiles was trying to copy over the same theme files it was reading.

Fix is incoming.

**Comment by AllanXu49** [comment] 2017-02-03 00:02
Thank you for investigating this.

**Closed as completed** 2017-02-06 21:17 UTC
Labels: ⚠️ Bug
