### ISSUE TITLE
GenerateFeeds.WithImageLink changing domain name

### ISSUE THREAD

**Issue by elvogel** [statiqdev/Statiq#629] opened 2018-02-16 20:57 UTC
I have the following set up to generate an RSS feed for the blog:
```
       GenerateFeeds().WithRssPath(ctx=> "blog/feed.rss")
            .WithRdfPath(ctx=> null).WithAtomPath(ctx => null)
            .WithFeedCopyright(ctx=> "2007-2017 Endpoint Systems. All rights reserved.")
            .WithFeedTitle(ctx=> "Endpoint Systems Blog")
            .WithFeedImageLink((ctx) => ctx.Get<string>("Image"))
            .WithFeedDescription(ctx=> "Talking points about endpoints")
            .WithFeedLink(ctx=> "https://endpointsystems.com/blog/")
            .WithItemPublished((doc, ctx) => doc["Published"]),
```
In an example blog post, I have this for my context data:
```
Title: Introducing Nancy.OWin.Security.B2C
Published: 1/16/2018
Categories: Nancy,OWin,Azure,AzureAD,AzureADB2C,Web,Nuget,GitHub
Description: We've released a NuGet package to simplify OpenID security against Azure AD B2C for Nancy OWin projects.
Image: "http://res.cloudinary.com/endpoint-systems/image/upload/q_auto:best/v1516124178/nancy-nuget_ge50tz.png"
```
Looking at my RSS feed XML, I'm seeing this:

```
		<item>
			<title>Introducing Nancy.OWin.Security.B2C</title>
			<link>https://endpointsystems.com/blog/introducing-nancy-owin-security-b2c</link>
			<description>We've released a NuGet package to simplify OpenID security against Azure AD B2C for Nancy OWin projects.</description>
			<enclosure url="https://endpointsystems.com/endpoint-systems/image/upload/q_auto:best/v1516124178/nancy-nuget_ge50tz.png" length="0" type="image" />
			<guid>https://endpointsystems.com/blog/introducing-nancy-owin-security-b2c</guid>
			<pubDate>Tue, 16 Jan 2018 00:00:00 GMT</pubDate>
		</item>
```
It's changing the domain name to the image. Is there a way to keep that from happening?

**Comment by daveaglick** [comment] 2018-02-28 00:36
This is definitely a bug - I’ll try to get it addressed in the next release.

**Comment by daveaglick** [comment] 2018-12-31 16:02
Finally getting around to looking at this. There's actually two things going on here...

The first is that you're specifying `.WithFeedImageLink()` in the module to use a string for the _feed_ image, but what you're really trying to do is use a string for the item image. You should (or also) set `.WithItemImageLink()` to a similar function. That'll work in your case.

The broader problem though is that the default item image function uses `IExecutionContext.GetLink()` which always assumes a local path and adds the domain. In that sense, it's working as intended. That's not really friendly though in a use case like this. I think the `IExecutionContext.GetLink()` methods should check for `http` as a prefix, or even just check for a fully-qualified URI, and assume that should be used wholesale if so. I'll look at making that change, after which this scenario should work out of the box without having to specify `.WithItemImageLink()` at all.

**Closed as completed** 2019-01-01 16:43 UTC
Labels: ⚠️ Bug
